var nodemailer = require('nodemailer');
var _ = require('underscore');

var FROM = 'CLUBPOINTZ Alerts <clubpointz@gmail.com>';
var TEXT_SUFFIX = '\n\nMessage generated by CLUBPOINTZ';
var DEFAULT_SUBJECT = 'CLUBPOINTZ Alert';
var USERS = ['jjgraham4@gmail.com'];

var AlertMailer = {

    getTransport : function () {
        return nodemailer.createTransport('SMTP', {
            service : 'Gmail',
            auth : {
                user : 'clubpointz@gmail.com',
                pass : 'cpabc123'
            }
        });
    },

    getMailOptions : function (user, subject, text) {
        return {
            from : FROM,
            to : user,
            subject : subject,
            text : text + TEXT_SUFFIX
        };
    },

    sendMessages : function (mailOptions) {
        var transport = this.getTransport();
        _.each(mailOptions, function (options) {
            console.log(options);
            transport.sendMail(options, function (error, response) {
                console.log('sent mail');
                if (error) {
                    console.log(error);
                } else {
                    console.log('Message sent: ' + response.message);
                }
            });
        });
    },

    mail : function (text, subject) {
        var subject = options.subject || DEFAULT_SUBJECT;
        var allMailOptions = [];
        _.each(USERS, function (user) {
            var mailOptions = this.getMailOptions(user, subject, text);
            allMailOptions.push(mailOptions);
        }, this);
        this.sendMessages(allMailOptions);
    }
};

exports.mailer = AlertMailer;
