var nodemailer = require('nodemailer');
var lib = require('./lib').lib;
var _ = require('underscore');

var TEXT_SUFFIX = '\n\n\n\nMessage generated by CLUBPOINTZ';
var DEFAULT_SUBJECT = 'CLUBPOINTZ Alert';
var FROM_NAME = 'CLUBPOINTZ';


var AlertMailer = {

    init : function () {
       this.emailUser = lib.getEnvVar('EMAIL_USER');
       this.emailPass = lib.getEnvVar('EMAIL_PASS');
       this.recipients = JSON.parse(lib.getEnvVar('RECIPIENTS'));
       this.from = FROM_NAME + '<' + this.emailUser + '>';
       this.pendingMessages = 0;

       return this;
    },

    _getTransport : function () {
        return nodemailer.createTransport('SMTP', {
            auth : {
                user : this.emailUser,
                pass : this.emailPass
            }
        });
    },

    _getMailOptions : function (user, subject, text) {
        return {
            from : this.from,
            to : user,
            subject : subject,
            text : text + TEXT_SUFFIX,
            html : ''
        };
    },

    _sendMessages : function (mailOptions) {
        var transport = this._getTransport();
        _.each(mailOptions, function (options) {
            this.pendingMessages = this.pendingMessages + 1;
            var that = this;
            transport.sendMail(options, function (error, response) {
                if (error) {
                    console.log(error);
                }
                that.pendingMessages = that.pendingMessages - 1;
            });
        }, this);
    },

    send : function (text, subject) {
        var subject = subject || DEFAULT_SUBJECT;
        var allMailOptions = [];

        _.each(this.recipients, function (user) {
            var mailOptions = this._getMailOptions(user, subject, text);
            allMailOptions.push(mailOptions);
        }, this);
        this._sendMessages(allMailOptions);
    },

    getPendingMessages : function () {
        return this.pendingMessages;
    }
};

exports.mailer = AlertMailer.init();
